name: CI
on: [push]

jobs:
  tests:
    name: ScenarioControl
    runs-on: ubuntu-20.04
    env:
      PATH_LICENSE_STRING: "2830898829&Courtesy&&&USR&45321&5_1_2021&1000&PATH&GEN&31_12_2025&0_0_0&6000&0_0"
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.8.5"
      - uses: julia-actions/cache@v1
        with:
          cache-registries: "true"
          cache-compiled: "true"
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: xvfb-run